- name: Install multimedia codecs
  ansible.builtin.include_tasks: codecs.yml

- name: Install multimedia player
  ansible.builtin.include_tasks: player.yml

- name: Install other multimedia packages
  ansible.builtin.include_tasks: etc.yml
